### ISSUE TITLE
Submit to keras-contrib + see Keras-FCN

### ISSUE THREAD

**Issue by ahundt** [nicolov/segmentation_keras#12]
Might you be interested in a pull request of this code to the official [keras-contrib](https://github.com/farizrahman4u/keras-contrib) repository?

These keras-contrib issues are also relevant to this repository:
 - https://github.com/farizrahman4u/keras-contrib/issues/47 incorporating coco + voc 2012
 - https://github.com/farizrahman4u/keras-contrib/issues/59 dealing with gaps in FCN training performance
 - https://github.com/farizrahman4u/keras-contrib/issues/63 training on other FCN networks

[Keras-FCN](https://github.com/aurora95/Keras-FCN), which I was planning to adapt for a merge into keras-contrib also has a SegDataGenerator implementation with some of the features you are looking for in your comments, plus additional models and experimental support for coco. My [Keras-FCN branch with a README.md](https://github.com/ahundt/Keras-FCN/tree/densenet_atrous) may also be informative, there is a pull request in progress to merge upstream.

**Comment by nicolov** [comment]
I'm def open to it.

How would you suggest going about that? Right now, it's not the cleanest/simplest code, as I've tried to match the original implementation as closely as possible.

**Comment by ahundt** [comment]
Update: François Chollet, Keras' author, said he is interested in directly incorporating dense prediction/FCN into the Keras API, so I'm seeking suggestions/feedback at https://github.com/fchollet/keras/issues/6538
