### ISSUE TITLE
i have downloaded the dataset,but i don't know how to use it

### ISSUE THREAD

**Issue by 541435721** [nicolov/segmentation_keras#16]
Thanks for sharing your codes.
i downloaded the dataset and the file has no suffi. I don't find any README in the package.
could you help me to solve this proplem? Thanks a lot.

**Comment by nicolov** [comment]
I'll try putting up a converted model so you can get started right away

**Comment by nicolov** [comment]
I've uploaded the converted model and updated the readme accordingly, please have a look.
