### ISSUE TITLE
docker running error

### ISSUE THREAD

**Issue by amiltonwong** [nicolov/segmentation_keras#19]
Hi, @nicolov ,

For the caffe weight conversion, I got the following error:

```
(tf_1.0) root@milton-All-Series:/data/code/segmentation_keras/conversion# docker run -v $(pwd):/workspace -ti `docker build -q .`
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
"docker run" requires at least 1 argument(s).
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
(tf_1.0) root@milton-All-Series:/data/code/segmentation_keras/conversion#

```

It shows that docker daemon is not running. Any other command should I input before it?

Thanks

**Comment by nicolov** [comment]
It seems a problem with your docker configuration. Make sure you can run
docker commands without sudo (follow the official docs about adding your
user to the docker group).

**Comment by amiltonwong** [comment]
I figure it out. I had to reboot the system to let  docker  service go up

**Comment by ivanzhovannik** [comment]
Hello Nicolo, I have got error like the one mentioned above. Reboot did not help

``$ docker run -v $(pwd):/workspace -ti `docker build -q .`
unable to prepare context: unable to evaluate symlinks in Dockerfile path: GetFileAttributesEx C:\Users\Hoofdman\Dockerfile: The system cannot find the file specified.
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...] [flags]

Run a command in a new container``

**Comment by nicolov** [comment]
It seems that you're running docker under windows, and I'm not really familiar with that - sorry. You might have more luck looking for docker/windows specific problems.

**Comment by ivanzhovannik** [comment]
I moved a bit further. Now I run the boot2docker Linux VM. And the error now is
`/usr/bin/env: 'python\r': No such file or directory`. I run VM via VirtualBox from Windows...

I am new to Linux. I tried to run `python -v` and `$sudo python -v`, but received `-sh: python: not found`
 If I check the PATH, there is no python.
But DockerFile runs `pip install tensorflow`, so it should contain python interpreter. If you have any ideas, please, share. :)

**Comment by nicolov** [comment]
I think the problem with this is that you edited some file with your
windows editor, which added an '\r' to the end of the line. I believe that
trying to get this to work with windows will lead to nothing but pain :D

**Comment by ivanzhovannik** [comment]
@nicolov I want to thank you for the work you did!
We fixed the Dockerfile for Windows. So, if anyone has a **caffe-tensorflow for Windows** transformation issue, please check out the link: https://github.com/ivanzhovannik/convert_caffe_windows
