### ISSUE TITLE
about the required pre-trained vgg model

### ISSUE THREAD

**Issue by amiltonwong** [nicolov/segmentation_keras#22]
Hi, @nicolov ,

According to this [line](https://github.com/nicolov/segmentation_keras/blob/master/train.py#L39), `vgg_conv.npy` is needed as pre-trained vgg model in training. Could you list the download location for corresponding caffemodel and prototxt file? And, is the conversion step the same as [here](https://github.com/nicolov/segmentation_keras/blob/master/conversion/README.md)?

Thanks!

**Comment by amiltonwong** [comment]
I can find the caffemodel from [here](https://github.com/fyu/dilation/blob/master/pretrained/download_vgg_conv.sh)
However, I couldn't find the prototxt file "vgg_conv.prototxt", any comments?

**Comment by nicolov** [comment]
Yes, I believe that's where I started the training from.

**Comment by knok** [comment]
I can use a prototext file from 
https://github.com/fyu/dilation/blob/master/models/dilation8_pascal_voc_deploy.prototxt,
according to the comment in model.py. It seems to work fine.

I got another prototext from https://raw.githubusercontent.com/ruimashita/caffe-train/master/vgg.deploy.prototxt,
it was not matched the shape on fc6 layer..

**Comment by nicolov** [comment]
Yes, I think that's what I used
