### ISSUE TITLE
tensorflow 1.3 support

### ISSUE THREAD

**Issue by MyVanitar** [nicolov/segmentation_keras#27]
Hello,

May I ask you to update the repo to the latest Tensorflow version?

**Comment by nicolov** [comment]
https://github.com/nicolov/segmentation_keras/commit/0f2366f0b4beeb6801ab91e2931c98cc5f20c472 bumps the version.

**Comment by Zumbalamambo** [comment]
@nicolov is it possible to initialise the weight initially and reuse it everytime for prediction for using it with flask?
