### ISSUE TITLE
IoU results

### ISSUE THREAD

**Issue by Barfknecht** [nicolov/segmentation_keras#28]
Have you by any chance compared this to the original implementation with regards to the mean IoU? 
If so, what implementation of IoU did you use and what were your results?

**Comment by nicolov** [comment]
Sorry, I have not done that, mostly because it would be pretty useless without the context module.

**Comment by Barfknecht** [comment]
Are you saying that purely because training of the context_module has not been implemented? In the original paper they still show that using the front end alone produces a mean IoU of 67.6% for the VOC-2012 dataset.

**Comment by nicolov** [comment]
Ah thanks, I forgot that they also show results without the context module.

**Comment by Barfknecht** [comment]
This is what I came up with to determine the confusion matrix, meanIOU and IOU. 

``` python
def calculate_iou(y_pred_batch, y_true_batch):
    conf_m = np.zeros((20, 20), dtype=float)
    for i in range(len(y_true_batch)):
        flat_pred = np.ravel(y_pred_batch[i]).astype(int)
        flat_label = np.ravel(y_true_batch[i]).astype(int)
        for p, l in zip(flat_pred, flat_label):
            if l == 0:
                continue
            if l < 20 and p < 20:
                conf_m[l, p] += 1
    I = np.diag(conf_m)
    U = np.sum(conf_m, axis=0) + np.sum(conf_m, axis=1) - I
    IOU = I/U
    meanIOU = np.mean(IOU)
    return conf_m, IOU, meanIOU
