### ISSUE TITLE
Slow prediction

### ISSUE THREAD

**Issue by Zumbalamambo** [nicolov/segmentation_keras#31]
The generation of mask is too slow. is there any ways to speed it up?

**Comment by nicolov** [comment]
IIRC, the interpolation was really slow. The [current code](https://github.com/nicolov/segmentation_keras/blob/master/utils/__init__.py#L29) is a pure-python port of the algorithm in the paper that I used to compare my results. You could try switching to a standard upsampling routine in scilab or pillow.
