### ISSUE TITLE
Problems with CuDNN library

### ISSUE THREAD

**Issue by Yuren-Zhong** [nicolov/segmentation_keras#32]
While running train.py, this is the error message:
`Epoch 1/20
E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 6021 (compatibility version 6000) but source was compiled with 5105 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
`

Since I don't have the root account, I can't install CuDNN v5. Do you know how I can fix this?
Thanks!

**Comment by nicolov** [comment]
Have you installed tensorflow 1.3 in a virtualenv as instructed? TF 1.3 should use CuDNN 6.

**Comment by Yuren-Zhong** [comment]
yes, I installed packages as instructed and the server has CuDNN 6
installed, but it seems CuDNN 5 is required.

**Comment by nicolov** [comment]
There was a typo in the readme, sorry. Make sure to `pip install tensorflow-gpu==1.3.0`.

**Comment by Yuren-Zhong** [comment]
Thanks, this fix my problem.
