### ISSUE TITLE
How do you determine the width and height of the input, and the size of the label_margin?

### ISSUE THREAD

**Issue by zhouhao-learning** [nicolov/segmentation_keras#35]
@nicolov 
Hello, I'd like to know if input_width, input_height, label_margin values are related to width, height of the picture? Do you have formulas or something like that?
Because I want to predict a new picture now, each picture of different sizes, some are large, some relatively small lot, which requires a different input_width, input_height, label_margin in size, that will not throw the error in "AssertionError". I try to use Image.resize method to predict the images, making them the size difference is not big, but I found that after the resize images and the size of the original picture of the forecast results are not the same, you can help me to answer this question? Thank you

**Comment by nicolov** [comment]
I think the best way to go would be to either crop or tile the images so that they're all the same size and match what the network expects.
