### ISSUE TITLE
Cannot locate Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by mongoose54** [nicolov/segmentation_keras#4]
Probably a rookie error but when I am trying to run the conversion step in [conversion](https://github.com/nicolov/segmentation_keras/tree/master/conversion) by running the docker I get the following error:

```
$sudo docker run -v $(pwd):/workspace -ti `docker build -q .`
time="2017-02-09T09:15:11-08:00" level=fatal msg="Cannot locate Dockerfile: Dockerfile" 
docker: "run" requires a minimum of 1 argument. See 'docker run --help'.
```

**Comment by nicolov** [comment]
Area you running from the `conversion` folder?

**Comment by mongoose54** [comment]
I was running the command outside the `conversion` folder . When I navigated to the  `conversion` folder I am getting the following error:  

```
docker run -v $(pwd):/workspace -ti `docker build -q .`time="2017-02-14T01:14:03-08:00" level=error msg="Can't exclude whole path, excluding pattern: *" 
time="2017-02-14T01:14:03-08:00" level=fatal msg="Post http:///var/run/docker.sock/v1.18/build?cpusetcpus=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&q=1&rm=1&t=: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?" 
docker: "run" requires a minimum of 1 argument. See 'docker run --help'.

I think it is an issue with Docker on my end. Is there a way to do the conversion without Docker?
```

**Comment by nicolov** [comment]
I am sure there is, you can actually just step through the commands in the
dockerfile and run them on your local machine. I'd highly suggest fixing
docker though, it'll come in handy often in the future.

**Comment by ivanzhovannik** [comment]
@mongoose54 , did you have a Dockerfile in the folder? I made a stupid mistake by just clonning /caffe-tensorflow without /segmentation_keras. I, therefore, got the mistake of Dockerfile absence in my folder.

@nicolov : As for such a person as me I would add two extra lines in README:
`git clone https://github.com/nicolov/segmentation_keras`
`cd /segmentation`
...
