### ISSUE TITLE
How to deal with unbalanced classes?

### ISSUE THREAD

**Issue by mrgloom** [nicolov/segmentation_keras#43]
Looks like your model is working with Pascal Voc dataset (20 classes + 1 background class), this dataset is unbalanced, if I remember correct, 'person' class is have dominant pixel area.

So my question is model use some additional tricks to deal with class unbalance?

**Comment by nicolov** [comment]
From my testing, it seems that the classes are balanced enough that the model can still learn. In some other projects, I've used class weighting to balance the number of samples between classes. This code does _not_ do this.
