### ISSUE TITLE
Failure running conversion through provided Docker container

### ISSUE THREAD

**Issue by asutic** [nicolov/segmentation_keras#44]
Hello,

While trying to experiment with the project, I ran into the issue with the conversion of the caffe model.

Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM bvlc/caffe:cpu
 ---> 0b577b836386
Step 2/4 : ENV MODEL_NAME dilation8_pascal_voc
 ---> Using cache
 ---> 75c63a3c3735
Step 3/4 : RUN pip install tensorflow
 ---> Running in 7ce61c615947
Collecting tensorflow
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32ca357d10>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/tensorflow/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32ca3573d0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/tensorflow/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32ca357310>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/tensorflow/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32ca357b90>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/tensorflow/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f32ca357d50>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/tensorflow/
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
The command '/bin/sh -c pip install tensorflow' returned a non-zero code: 1

Any recommendations on how to fix the problem?

**Comment by nicolov** [comment]
I believe that your internet connection is broken or doesn't work with
docker (common if you have proxies, dns issues, etc..)

**Comment by asutic** [comment]
Thanks for pointing out. Putting ENV HTTP_PROXY into Dockerfile solved the issue. predict.py produces the segmentation result correctly.
