### ISSUE TITLE
Weights Conversion Error: wget: unable to resolve host address 'vobj.cs.princeton.edu'

### ISSUE THREAD

**Issue by kaisark** [nicolov/segmentation_keras#46]
I ran into a download error while converting the model weights. Please confirm the download link.

Thanks.

(dl4cvpy3) ubuntu@ip-172-31-0-76:\~/cviz/segmentation_keras/conversion$ wget http://vobj.cs.princeton.edu/models/dilation8_pascal_voc.caffemodel
--2018-12-30 18:45:11--  http://vobj.cs.princeton.edu/models/dilation8_pascal_voc.caffemodel
Resolving vobj.cs.princeton.edu (vobj.cs.princeton.edu)... failed: Name or service not known.
wget: unable to resolve host address 'vobj.cs.princeton.edu'

**Comment by nicolov** [comment]
Thanks for reaching out. I've updated the link to http://dl.yf.io/dilation/models/dilation8_pascal_voc.caffemodel

**Comment by kaisark** [comment]
Thanks. I was able to get everything working using Keras 2.0.8/Tensorflow-GPU 1.4.0. 

Note:
I just ran into a few Keras API version warnings...

------------------------------------------
(dl4cvpy3) ubuntu@ip-172-31-0-76:~/cviz/segmentation_keras$ python predict.py --weights_path conversion/converted/dilation8_pascal_voc.npy --input_path images/minicooper.jpg 
Using TensorFlow backend.
/home/ubuntu/cviz/segmentation_keras/model.py:15: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), input_shape=(900, 900,..., name="conv1_1", activation="relu")`
  model.add(Convolution2D(64, 3, 3, activation='relu', name='conv1_1', input_shape=(input_width, input_height, 3)))
/home/ubuntu/cviz/segmentation_keras/model.py:16: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), name="conv1_2", activation="relu")`
  model.add(Convolution2D(64, 3, 3, activation='relu', name='conv1_2'))
/home/ubuntu/cviz/segmentation_keras/model.py:19: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), name="conv2_1", activation="relu")`
  model.add(Convolution2D(128, 3, 3, activation='relu', name='conv2_1'))
/home/ubuntu/cviz/segmentation_keras/model.py:20: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), name="conv2_2", activation="relu")`
  model.add(Convolution2D(128, 3, 3, activation='relu', name='conv2_2'))
/home/ubuntu/cviz/segmentation_keras/model.py:23: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), name="conv3_1", activation="relu")`
  model.add(Convolution2D(256, 3, 3, activation='relu', name='conv3_1'))
/home/ubuntu/cviz/segmentation_keras/model.py:24: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), name="conv3_2", activation="relu")`
  model.add(Convolution2D(256, 3, 3, activation='relu', name='conv3_2'))
/home/ubuntu/cviz/segmentation_keras/model.py:25: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), name="conv3_3", activation="relu")`
  model.add(Convolution2D(256, 3, 3, activation='relu', name='conv3_3'))
/home/ubuntu/cviz/segmentation_keras/model.py:28: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), name="conv4_1", activation="relu")`
  model.add(Convolution2D(512, 3, 3, activation='relu', name='conv4_1'))
/home/ubuntu/cviz/segmentation_keras/model.py:29: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), name="conv4_2", activation="relu")`
  model.add(Convolution2D(512, 3, 3, activation='relu', name='conv4_2'))
/home/ubuntu/cviz/segmentation_keras/model.py:30: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), name="conv4_3", activation="relu")`
  model.add(Convolution2D(512, 3, 3, activation='relu', name='conv4_3'))
/home/ubuntu/.virtualenvs/dl4cvpy3/lib/python3.5/site-packages/keras/legacy/layers.py:755: UserWarning: The `AtrousConvolution2D` layer  has been deprecated. Use instead the `Conv2D` layer with the `dilation_rate` argument.
  warnings.warn('The `AtrousConvolution2D` layer '
/home/ubuntu/.virtualenvs/dl4cvpy3/lib/python3.5/site-packages/keras/legacy/layers.py:759: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu", name="conv5_1", dilation_rate=(2, 2))`
  return Conv2D(*args, **kwargs)
/home/ubuntu/.virtualenvs/dl4cvpy3/lib/python3.5/site-packages/keras/legacy/layers.py:759: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu", name="conv5_2", dilation_rate=(2, 2))`
  return Conv2D(*args, **kwargs)
/home/ubuntu/.virtualenvs/dl4cvpy3/lib/python3.5/site-packages/keras/legacy/layers.py:759: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu", name="conv5_3", dilation_rate=(2, 2))`
  return Conv2D(*args, **kwargs)
/home/ubuntu/.virtualenvs/dl4cvpy3/lib/python3.5/site-packages/keras/legacy/layers.py:759: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(4096, (7, 7), activation="relu", name="fc6", dilation_rate=(4, 4))`
  return Conv2D(*args, **kwargs)
/home/ubuntu/cviz/segmentation_keras/model.py:43: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(4096, (1, 1), name="fc7", activation="relu")`
  model.add(Convolution2D(4096, 1, 1, activation='relu', name='fc7'))
/home/ubuntu/cviz/segmentation_keras/model.py:46: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(21, (1, 1), name="fc-final", activation="linear")`
  model.add(Convolution2D(21, 1, 1, activation='linear', name='fc-final'))
2019-01-11 00:11:57.865213: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-01-11 00:12:00.414688: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-11 00:12:00.415183: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.11GiB
2019-01-11 00:12:00.415213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
Saving results to:  images/minicooper_seg.png

![minicooper](https://user-images.githubusercontent.com/3580312/51005663-c5df1380-150d-11e9-831b-892c864b4082.jpg)

![minicooper_seg](https://user-images.githubusercontent.com/3580312/51005669-ca0b3100-150d-11e9-9771-eb750134cb4e.png)

**Comment by nicolov** [comment]
Thanks, I'll have a look at them.
