### ISSUE TITLE
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by ghost** [nicolov/segmentation_keras#48]

**Comment by nicolov** [comment]
Make sure that you're following the instructions. Install the dependencies into a fresh virtualenv using `pip install -r requirements.txt` to get the exact same versions the code was tested with.

**Comment by ghost** [comment]
ERROR: Could not find a version that satisfies the requirement tensorflow==1.3.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0)
ERROR: No matching distribution found for tensorflow==1.3.0
