### ISSUE TITLE
Questions on training part

### ISSUE THREAD

**Issue by AminFefe** [nicolov/segmentation_keras#7]
Hi Nicolov, 

Thanks a lot for this nice work, it's been of great help to me. 

I would like to get your opinion on various topics regarding training part:
- can you provide some insights on how to have a system returning image size results ? (instead of 16*16)
- to adapt to a problem with only two classes (say foreground/background), I only changed every 21 to 2 in the code, but the results are not as nice as I expected for now... Am I doing smth wrong ?
- do you suggest fixing the weights of the first layers or not ?
- I'm currently working on data augmentation to add elastic deformations, do you plan to add it as well ? I could share it once it's done.

Thanks a lot

**Comment by nicolov** [comment]
Glad to be of help.

1. With the current architecture, the only thing you can do is feed in
larger images. If you wanted to, you could implement the context network
shown in the paper, that adds ~4x upsampling. In practice, however, you
could probably get decent results with a rough upsampling.

2. That should be enough. Make sure that your data is normalized properly.

3. I usually don't

4. That's cool, what paper are you basing the implementation off?
